version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: postgres-db-online-library
    env_file:
      - db-env.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
